import Head from 'next/head'
import Image from 'next/image'
import type { NextPage } from 'next'
import { useDispatch, useSelector } from 'react-redux'
import styles from '../styles/Home.module.css'
import { AppState } from '../src/general-type'
import { addToParameter } from '../src/action';
import { minusToParameter } from '../src/action';
import Todos from '../src/components/todos';

const Home: NextPage = () => {

  // توسط selector میتوانیم داده ها را بگیریم و نمایش دهیم
  // توسط dispatch میتوانیم به آن مقادیر ارسال کنیم
  const
    state = useSelector((state: AppState) => state.parameter) | 0,
    dispatch = useDispatch(),

    //تابع ما که توسط یک value آن را ارسال میکنیم 
    // value همان payload میشود
    clicPlusHandler = () => {
      dispatch(addToParameter(5))
    },

    clicMinusHandler = () => {
      dispatch(minusToParameter(2))
    };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {state}
        </h1>

        <button onClick={clicPlusHandler}>++</button>
        <button onClick={clicMinusHandler}>--</button>
      </main>
      <Todos />
    </div>
  )
}

export default Home
